// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Szinkronstudio.Data;

#nullable disable

namespace Szinkronstudio.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Szinkronstudio.Data.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CategoryModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Romantic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cartoon"
                        });
                });

            modelBuilder.Entity("Szinkronstudio.Data.MovieModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("AnnouncedInHungary")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DubProducer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Versenyzok");

                    b.HasData(
                        new
                        {
                            Id = "2020/15",
                            CategoryId = 4,
                            DubProducer = "John Doe",
                            Length = 126,
                            Title = "Johnny and the Two A**holes"
                        },
                        new
                        {
                            Id = "1998/315",
                            CategoryId = 5,
                            DubProducer = "Ben Dover",
                            Length = 234,
                            Title = "Nature of Harambe"
                        },
                        new
                        {
                            Id = "1972/521",
                            CategoryId = 2,
                            DubProducer = "Bull Shark Testosterone",
                            Length = 79,
                            Title = "Space Amoeba"
                        },
                        new
                        {
                            Id = "2004/032",
                            CategoryId = 3,
                            DubProducer = "Carl Johnson",
                            Length = 96,
                            Title = "Gangs of the Grove Street"
                        },
                        new
                        {
                            Id = "1920/915",
                            CategoryId = 1,
                            DubProducer = "Adolf Stalin",
                            Length = 135,
                            Title = "My Fellow Jonathan"
                        },
                        new
                        {
                            Id = "2020/14",
                            CategoryId = 6,
                            DubProducer = "US Government",
                            Length = 71,
                            Title = "Mickey and the Nazis"
                        });
                });

            modelBuilder.Entity("Szinkronstudio.Data.MovieModel", b =>
                {
                    b.HasOne("Szinkronstudio.Data.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
